= Enterprise Clojure Training

"Clojure is serious business!"
-- Timothy Pratley

A Clojure training course for Developers and Senior Developers working on Enterprise software.

Please visit the https://timothypratley.github.io/enterprise-clojure-training[Website].

A list of companies and individuals offering Clojure training is here https://clojure.org/community/training[this page].

See https://timothypratley.github.io/enterprise-clojure-training/manual.html[manual.html].
or https://timothypratley.github.io/enterprise-clojure-training/manual.pdf[manual.pdf].
for the course material, and https://github.com/timothypratley/enterprise-clojure-training/tree/master/examples[example code].


== Rationale

Clojure has been in the "adopt" zone of the Thoughtworks tech radar since 2014.
But companies face the challenge of how to prepare their staff to be productive using Clojure.
Creating a structured enterprise style course material will enable more people to offer Clojure courses suitable for companies wanting to adopt Clojure.


== Usage

Slides have https://github.com/hakimel/reveal.js/wiki/Keyboard-Shortcuts[Keyboard shortcuts].


== Contributing

If you have suggestions on how to improve this course, I would love to hear them.
Issues welcome. Pull requests welcome.


== Developing

The manual and slides source material are under the `docs` directory.
The material is written in asciidoc (.adoc) format, which gets compiled to HTML and PDF.
They are built to HTML and PDF using https://asciidoctor.org[Asciidoctor], and output to the `site` directory.
Refer to the https://asciidoctor.org/docs/asciidoc-writers-guide[Writer's Guide] for syntax.
Asciidoctor provides excellent document producing features and allows slides to be generated as RevealJS slideshows.

When editing the material, there are many live preview tools to chooose from https://asciidoctor.org/docs/editing-asciidoc-with-live-preview[here].
I use the IntelliJ plugin as it is simple to install and works well.
There is also a `./watch.sh` command to build when the source file changes.
The Web (Epiphany) browser reloads from disk when the HTML file changes.


=== Building

You can install asciidoctor, asciidoctor-pdf, and ascidoctor-revealjs locally and run

    ./build.sh

But installing these tools is a bit of a pain... so two ways to get the dependencies are provided:


==== The Ruby way

Requires https://www.ruby-lang.org/en/documentation/installation[Ruby].

You don't need to install Asciidoctor.
Asciidoctor is a dependency specified in the Gemfile.
However you will need Ruby and Bundler to pull down the Asciidoctor and RevealJS plugin dependencies.

Requires Bundler:

    gem install bundler

Pull the dependencies:

    bundle --path=.bundle/gems --binstubs=.bundle/.bin

Now you can call the build script:

    bundle exec ./build.sh

To have the build watch for file changes and rebuild automatically:

    ./watch.sh

You need entr installed for watch to work, I highly recomend it.


==== The Docker way

Alternatively, if you prefer pulling a Docker image over installing dependencies:

    docker run -v $(pwd):/documents/ asciidoctor/docker-asciidoctor /documents/build.sh


== Deploying

TravisCI automatically deploys the latest version to https://timothypratley.github.io/enterprise-clojure-training[GitHub Pages].
image:https://travis-ci.org/timothypratley/enterprise-clojure-training.svg?branch=master[Build Status, link=https://travis-ci.org/timothypratley/enterprise-clojure-training]

Manual deployment:

    ./deploy.sh
