= Enterprise Clojure Training

"Clojure is serious business!"
-- Timothy Pratley

This is a Clojure training course for Developers and Senior Developers working on Enterprise software.
The site is hosted https://timothypratley.github.io/enterprise-clojure-training[here].
See https://timothypratley.github.io/enterprise-clojure-training/manual.html[manual.html]
or https://timothypratley.github.io/enterprise-clojure-training/manual.pdf[manual.pdf]
for the course material, and https://github.com/timothypratley/enterprise-clojure-training/tree/master/examples[example code].
A list of companies and individuals offering Clojure training is here https://clojure.org/community/training[this page].


== Rationale

Clojure has been in the "adopt" zone of the Thoughtworks tech radar for some time now.
But companies face the challenge of how to prepare their staff to be productive using Clojure.
Creating a structured enterprise style course material will enable more people to offer Clojure courses suitable for companies wanting to adopt Clojure.


== Contributing

If you have suggestions on how to improve this course, I would love to hear them.
Issues welcome. Pull requests welcome.


== Building

Requires Ruby and Bundler to be installed.

Pull the dependencies:

    bundle --path=.bundle/gems --binstubs=.bundle/.bin

The manual and slides are under the `docs` directory.
They are built to HTML and PDF using https://asciidoctor.org[Asciidoctor], and output to the `site` directory.

    ./build.sh


== Deploying

    ./deploy.sh

The built HTML and PDF are hosted on https://timothypratley.github.io/enterprise-clojure-training[GitHub Pages].
