= Enterprise Clojure Training

"Clojure is serious business!"
-- Timothy Pratley

This is a Clojure training course for Developers and Senior Developers working on Enterprise software.
The site is hosted https://timothypratley.github.io/enterprise-clojure-training[here].
See https://timothypratley.github.io/enterprise-clojure-training/manual.html[manual.html]
or https://timothypratley.github.io/enterprise-clojure-training/manual.pdf[manual.pdf]
for the course material, and https://github.com/timothypratley/enterprise-clojure-training/tree/master/examples[example code].
A list of companies and individuals offering Clojure training is here https://clojure.org/community/training[this page].


== Rationale

Clojure has been in the "adopt" zone of the Thoughtworks tech radar for some time now.
But companies face the challenge of how to prepare their staff to be productive using Clojure.
Creating a structured enterprise style course material will enable more people to offer Clojure courses suitable for companies wanting to adopt Clojure.


== Contributing

If you have suggestions on how to improve this course, I would love to hear them.
Issues welcome. Pull requests welcome.


== Developing

The manual and slides source material are under the `docs` directory.
The material is written in asciidoc (.adoc) format, which gets compiled to HTML and PDF.
They are built to HTML and PDF using https://asciidoctor.org[Asciidoctor], and output to the `site` directory.
Refer to the https://asciidoctor.org/docs/asciidoc-writers-guide[Writer's Guide] for syntax.
Asciidoctor provides excellent document producing features and allows slides to be generated as RevealJS slideshows.

When editing the material, there are many live preview tools to chooose from https://asciidoctor.org/docs/editing-asciidoc-with-live-preview[here].
I use the IntelliJ plugin as it is simple to install and works well.


== Building

You don't need to install Asciidoctor.
It is used as a dependency specified in this project's Gemfile.
However you will need Ruby and Bundler to pull down the Asciidoctor and RevealJS plugin dependencies.

Requires Ruby:

    https://www.ruby-lang.org/en/documentation/installation

Requires Bundler:

    gem install bundler

Pull the dependencies:

    bundle --path=.bundle/gems --binstubs=.bundle/.bin

Now you can call the build script:

    ./build.sh


== Deploying

    ./deploy.sh

The built HTML and PDF are hosted on https://timothypratley.github.io/enterprise-clojure-training[GitHub Pages].
